import { type SQL, sql } from "drizzle-orm";
import { type AnyPgColumn, timestamp, uuid } from "drizzle-orm/pg-core";

/** Primary key: a random UUID generated by the database. */
export const id = () => uuid("id").primaryKey().defaultRandom();

/**
 * Audit timestamps, stored as UTC instants (`timestamptz`). `updated_at` is
 * refreshed by the ORM on every update.
 */
export const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
};

const CONTROLLED_VALUE = /^[a-z0-9]+(-[a-z0-9]+)*$/;

/**
 * CHECK expression restricting a text column to a fixed vocabulary.
 *
 * Controlled values are text plus a CHECK rather than PostgreSQL enums: adding
 * or retiring a value is then an ordinary migration, with none of the
 * restrictions of `ALTER TYPE`.
 */
export function oneOf(column: AnyPgColumn, values: readonly string[]): SQL {
  for (const value of values) {
    // Values are inlined into DDL, so only plain kebab-case literals are allowed.
    if (!CONTROLLED_VALUE.test(value)) {
      throw new Error(`Invalid controlled value: ${value}`);
    }
  }
  const literals = values.map((value) => sql.raw(`'${value}'`));
  return sql`${column} in (${sql.join(literals, sql`, `)})`;
}

/** CHECK expression for URL-safe slugs such as "public-health" or "2026-fall". */
export function isSlug(column: AnyPgColumn): SQL {
  return sql`${column} ~ '^[a-z0-9]+(-[a-z0-9]+)*$'`;
}
