import {
  type Database,
  authAccounts,
  authRateLimits,
  authSessions,
  authVerifications,
  users,
} from "@medos/database";
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { APIError } from "better-auth/api";

import { MAX_PASSWORD_LENGTH, MIN_PASSWORD_LENGTH } from "@/features/auth/messages";

import { type AuthConfig, isEmailAllowed } from "./config";
import { AUTH_COOKIE_PREFIX } from "./routes";

const DAY = 60 * 60 * 24;

/**
 * Builds the authentication service (Better Auth) on top of the MedOS
 * database. Nothing here is custom cryptography: password hashing (scrypt),
 * session tokens, OAuth and CSRF protection are the framework's.
 *
 * MedOS only decides policy: which sign-in methods exist, how long sessions
 * last, who may create an account, and which tables hold the data.
 */
export function createAuth(db: Database, config: AuthConfig) {
  return betterAuth({
    appName: "MedOS",
    secret: config.secret,
    baseURL: config.baseURL,

    database: drizzleAdapter(db, {
      provider: "pg",
      // The framework's "user" is the MedOS user: one record, not two.
      schema: {
        user: users,
        session: authSessions,
        account: authAccounts,
        verification: authVerifications,
        rateLimit: authRateLimits,
      },
    }),
    user: { fields: { name: "displayName" } },

    emailAndPassword: {
      enabled: true,
      minPasswordLength: MIN_PASSWORD_LENGTH,
      maxPasswordLength: MAX_PASSWORD_LENGTH,
      autoSignIn: true,
    },

    // Registered only when credentials exist, so a missing Google setup cannot half-work.
    socialProviders: config.google
      ? { google: { clientId: config.google.clientId, clientSecret: config.google.clientSecret } }
      : {},

    account: {
      // MedOS never calls Google on the user's behalf; tokens at rest are encrypted regardless.
      encryptOAuthTokens: true,
      /*
       * Account linking is left at the framework's safe default: a Google
       * sign-in is attached to an existing account only if that account's
       * email is already verified. An unverified email-and-password account
       * is therefore never merged with a Google identity automatically.
       */
    },

    session: {
      expiresIn: 7 * DAY,
      // An active session is extended at most once a day.
      updateAge: DAY,
    },

    rateLimit: {
      enabled: config.production,
      // Counters live in the database so limits hold across server instances.
      storage: "database",
    },

    advanced: {
      cookiePrefix: AUTH_COOKIE_PREFIX,
      // Stated explicitly: the framework relaxes these by default when NODE_ENV is "test".
      disableOriginCheck: false,
      disableCSRFCheck: false,
      // Identifiers are UUIDs generated by PostgreSQL, like every other MedOS table.
      database: { generateId: "uuid" },
    },

    databaseHooks: {
      user: {
        create: {
          // Applies to every way of creating a user: sign-up and first Google sign-in alike.
          before: async (user) => {
            if (!isEmailAllowed(config, user.email)) {
              throw new APIError("FORBIDDEN", { message: "This account cannot be created." });
            }
          },
        },
      },
    },

    telemetry: { enabled: false },
  });
}

export type Auth = ReturnType<typeof createAuth>;
